---
title: "References"
---

This is not a complete list of references, but rather some that you may find handy while learning reproduction assessments.

### Oocyte morphology and stages

[Grier et al 2009](https://drive.google.com/file/d/1MJirlMNcLLaBZ9aURPMoeFdBtfHLGP0m/view?usp=sharing). The ovary, folliculogenesis, and oogenesis in teleosts.

[Grier et al 2018](https://drive.google.com/file/d/1eY4SvbUGQpgZLzZjjnm9TfnpWsyo-SEz/view?usp=sharing)  Oocyte Development and Staging in the Florida Bass, *Micropterus floridanus* (LeSueur, 1822), with Comments on the Evolution of Pelagic and Demersal Eggs in Bony Fishes. Reference has detailed images of oocyte morphology.

[McMillen 2007](https://drive.google.com/file/d/1mr4707-4xYwvHbjOXYGYBGFn-ECvmsd1/view?usp=sharing) Female reproductive systems.

[Wallace & Selman 1981](https://drive.google.com/file/d/17avAWpmcmOy8oz1s469RysmUQ3yCZ5K7/view?usp=sharing) Cellular and dynamic aspects of oocyte growth in teleosts.

### Spermatogenesis
[Schulz et al. 2009](https://drive.google.com/file/d/1t1tf9ZTSfjsHrVpTXzSXhWpf3wLJyFhO/view?usp=sharing) Spermatogenesis in fish.

### Hermaphroditism 
[Sadovy & Shapiro 1987](https://drive.google.com/file/d/1vPkSpAwjbB03KSUeUZ1b67WLiFhP8cdt/view?usp=sharing) Criteria for the diagnosis of hermaphroditism in fishes.

[Nakamura et al. 2005](https://drive.google.com/file/d/1dhStmOWPnOMz65w2LBPF34qA55F-Jgvk/view?usp=sharing) Sex change in coral reef fish.

### Histology
[Atlas of fish histology and histopathology](https://studylib.net/doc/8727800/atlas-of-fish-histology-and-histopathology). Authors: Galit Sharon and Dina Zilberg.

[Fish Histology Manual v4](chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://trainingcenter.fws.gov/resources/course-resources/fish-histology/Fish_Histology_Manual_v4.pdf). Contributing authors: Sonia Mumford; Jerry Heidel; Charlie Smith; John Morrison; Beth MacConnell; Vicki Blazer.

[4th Workshop on gonadal histology of fishes](https://digital.csic.es/handle/10261/24937?locale=en). Wyanski, D. M. and N. Brown-Peterson. 

[Education Guide: Special Stains and H & E Second Edition](chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://www.agilent.com/cs/library/technicaloverviews/public/08066_special_stains_eduguide.pdf). Editors: Kumar, G. L. and J. A. Kiernan eds. This is a guide to stains that is not fish specific.

### Fecundity

[Thorsen & Kjesbu 2001](https://drive.google.com/file/d/1vKhqiiosk-aV25EX2Pn8jJchnSPQZyEo/view?usp=sharing). A rapid method for estimation of oocyte size and potential fecundity.

[Arthur et al 2022](https://drive.google.com/file/d/1abJgJZgJMMtTuVDMaBN-f3OAVCjN3OIJ/view?usp=sharing) Alaskan Yelloweye Rockfish Fecundity Revealed through an Automated Egg Count and Digital Imagery Method.